services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - 3000:3000
    environment:
      - CI=true
      - NODE_ENV=production
      - PORT=3000
    depends_on:
      - admin
  admin:
    container_name: admin
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
    ports:
      - 3001:3000
    environment:
      - CI=true
      - NODE_ENV=production
      - PORT=3001